//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 10:23:22 PM EET 
//


package Brains;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FXYCoefs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="XYCoef" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="FX" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="FY" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GXYCoefs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="XYCoef" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="GX" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="GY" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fxyCoefs",
    "gxyCoefs"
})
@XmlRootElement(name = "DichData")
public class DichData {

    @XmlElement(name = "FXYCoefs", required = true)
    protected FXYCoefs fxyCoefs;
    @XmlElement(name = "GXYCoefs", required = true)
    protected GXYCoefs gxyCoefs;

    /**
     * Gets the value of the fxyCoefs property.
     * 
     * @return
     *     possible object is
     *     {@link FXYCoefs }
     *     
     */
    public FXYCoefs getFXYCoefs() {
        return fxyCoefs;
    }

    /**
     * Sets the value of the fxyCoefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link FXYCoefs }
     *     
     */
    public void setFXYCoefs(FXYCoefs value) {
        this.fxyCoefs = value;
    }

    /**
     * Gets the value of the gxyCoefs property.
     * 
     * @return
     *     possible object is
     *     {@link GXYCoefs }
     *     
     */
    public GXYCoefs getGXYCoefs() {
        return gxyCoefs;
    }

    /**
     * Sets the value of the gxyCoefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GXYCoefs }
     *     
     */
    public void setGXYCoefs(GXYCoefs value) {
        this.gxyCoefs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="XYCoef" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="FX" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="FY" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "xyCoef"
    })
    public static class FXYCoefs {

        @XmlElement(name = "XYCoef", required = true)
        protected List<XYCoef> xyCoef;

        /**
         * Gets the value of the xyCoef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the xyCoef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getXYCoef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XYCoef }
         * 
         * 
         */
        public List<XYCoef> getXYCoef() {
            if (xyCoef == null) {
                xyCoef = new ArrayList<XYCoef>();
            }
            return this.xyCoef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="FX" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="FY" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class XYCoef {

            @XmlAttribute(name = "FX", required = true)
            protected double fx;
            @XmlAttribute(name = "FY", required = true)
            protected double fy;

            /**
             * Gets the value of the fx property.
             * 
             */
            public double getFX() {
                return fx;
            }

            /**
             * Sets the value of the fx property.
             * 
             */
            public void setFX(double value) {
                this.fx = value;
            }

            /**
             * Gets the value of the fy property.
             * 
             */
            public double getFY() {
                return fy;
            }

            /**
             * Sets the value of the fy property.
             * 
             */
            public void setFY(double value) {
                this.fy = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="XYCoef" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="GX" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="GY" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "xyCoef"
    })
    public static class GXYCoefs {

        @XmlElement(name = "XYCoef", required = true)
        protected List<XYCoef> xyCoef;

        /**
         * Gets the value of the xyCoef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the xyCoef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getXYCoef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XYCoef }
         * 
         * 
         */
        public List<XYCoef> getXYCoef() {
            if (xyCoef == null) {
                xyCoef = new ArrayList<XYCoef>();
            }
            return this.xyCoef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="GX" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="GY" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class XYCoef {

            @XmlAttribute(name = "GX", required = true)
            protected double gx;
            @XmlAttribute(name = "GY", required = true)
            protected double gy;

            /**
             * Gets the value of the gx property.
             * 
             */
            public double getGX() {
                return gx;
            }

            /**
             * Sets the value of the gx property.
             * 
             */
            public void setGX(double value) {
                this.gx = value;
            }

            /**
             * Gets the value of the gy property.
             * 
             */
            public double getGY() {
                return gy;
            }

            /**
             * Sets the value of the gy property.
             * 
             */
            public void setGY(double value) {
                this.gy = value;
            }

        }

    }

}
